version: '3'

services:
  ssh-proxy:
    image: golang:latest
    ports:
      - 2222:2222
    volumes:
      - ../sshr:/go/src/github.com/tsurubee/sshr
    working_dir: /go/src/github.com/tsurubee/sshr
    command: make server